### ISSUE TITLE
Navbar alignment issue on standard screen size

### ISSUE THREAD

**Issue by techrevrit** [sharozijaz/transport#2]
![image](https://user-images.githubusercontent.com/110258794/187625053-7a060b0c-77f2-47d7-97b0-87832ff9a541.png)

Navbar should follow box model because design for web UI is box model based, all other divs should respect box model

**Comment by sharozijaz** [comment]
![image](https://user-images.githubusercontent.com/46896548/187644194-eb7c7c3c-2bd8-4596-b91c-4d47fdfcb2e9.png)
